title:              FEMEDIA
email:              #your-email@example.com
description:        Analysis of female represenation in US written online media
author:             #Start Bootstrap
baseurl:            ""
url:                "https://vfayt99.github.io/femedia/"

# Social Profiles
twitter_username:   #SBootstrap
github_username:    #StartBootstrap
facebook_username:  #StartBootstrap
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google#_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
theme: jekyll-theme-clean-blog
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

